version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    restart: always

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ignite

  ignite:
    container_name: ignite
    image: ignite
    volumes:
      - "./ignite/config.toml:/ignite/config.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - VIRTUAL_HOST=change.me
    ports:
      - "5000:5000"
    restart: always

  ignite-admin:
    container_name: ignite-admin
    image: ignite-admin
    volumes:
      - "./ignite-admin/config.toml:/ignite-admin/config.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - VIRTUAL_HOST=change.me
    ports:
      - "8000:8000"
    restart: always

  ignite-stats:
    container_name: ignite-stats
    image: ignite-stats
    volumes:
      - "./ignite-stats/config.toml:/ignite-stats/config.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
