[app]
address = ":5000"

[db]
driver = "mysql"
connect = "root:@tcp(mysql:3306)/ignite?charset=utf8"

[ss]
image = "registry.xiaozhou.net/ssmu:latest"

[host]
address = "localhost"
from = 4000
to = 6000
